---
title: "Homework"
---

## Description
There will be four homework assignments throughout the semester to ensure that you are learning the materials.  
Homework assignments will be assigned throughout the semester and due before class the following week.  The lowest two grades will be dropped.  Assignments will be provided via UBLearns as R scripts with embedded questions. It will look something like this:

```
#' ## Question 1
#' Load the iris dataset by running
## ------------------------------------------------------------------------
data(iris)
#' > How many observations (rows) are there for the versicolor species?
#' _______________________
#' 
#' ## Question 2
#' Create a vector with the following values:  23, 45, 12, 89 
#' Then multiply each element of the vector by 15.  
#' 
#' > What is the standard deviation of the new vector? 
```

You can open the R script in RStudio and write the code needed to answer each question.    Your work will be uploaded to UBLearns with multiple choice or numeric answers for each question.  Your your R/RMarkdown script will also be uploaded as the response to the final ‘question’.  Your script will not be graded, but will be taken into account if there are any questions about the assignment or grading.  UBLearns will prevent  submission of homework after class starts, so be sure to get it in on time.  

You are welcome to work collaboratively on homework assignments but you are responsible for developing your own code to answer the questions.  So an acceptable question to ask a classmate would be, “which functions did you use to answer number 4?,” while an unacceptable question would be “please email me your code for question #4.”    
Some homework assignments will have  a bonus question that builds upon material covered in class but is more complicated than the homework questions.  These will be worth additional point(s).  

See [Syllabus for more information.](Syllabus.html)  