---
title: "GEO503: R Data Science"
subtitle: "Introduction to R for Data Science"
output:
  html_document:
    css: styles.css
    self_contained: no
    toc_float: no
---

Professor <a href="http://adamwilson.us"> Adam M. Wilson </a><br>
Department of Geography, & Graduate Program in Evolution, Ecology and Behavior <br> 
University at Buffalo, Buffalo, NY

<i class="fa fa-exclamation-triangle" style="color:red" aria-hidden="true"></i> This website is currently under construction and does not contain the full materials for the course.  It will not be completed until August 2016.

## Description
The quantity and quality of data available for ecological and environmental research has exploded over the past few decades. These ‘big data’ now allow us to address important questions (both old and new) with unprecedented rigor and generality.  Leveraging these new data streams requires new tools and increasingly sophisticated workflows. The free and open-source R programming language has become a lingua franca for ecological, epidemiological, and statistical research.  The course will use a combination of lecture and hands-on exercises to provide a gentle introduction to programming in R with a focus on spatial data processing.  The use of ‘literate programming’ (code embedded within text) to generate dynamic, reproducible research output (figures, manuscripts, websites, etc.) will also be addressed. The course includes an extensive project for students to conduct spatial analysis related to their research. Familiarity with basic GIS concepts (raster, vector, geographic projection, etc.) will be assumed, but no prior experience with R is necessary.  The course is open to advanced undergraduate students and graduate students (postdocs are also welcome) with an interest in advancing their data analysis and modeling skill-set. 

# Course Content
Course content is designed to be flexible to accommodate student interest and abilities.  The order and timing of course topics may change as the semester progresses.  

1. **Introduction & Overview**:
        Course Motivation & Objectives. Workflow & repeatable research in an era of big data for spatial       
        environmental analysis.  Getting started with the R Project for Statistical Computing & RStudio.     
2. **Data Gymnastics**:
        Data structures (vectors, matrices, data frames). Base graphics. Reading and writing data (from disk            and internet). For loops, conditional statements, and custom functions.   Data gymnastics with dplyr.
3. **Reproducible Research & Literate Programming**:
        Introduction to rmarkdown, creation of dynamic research outputs. Publishing to github/word/html/etc. Brief introduction to pandoc.
4. **Version Control**: Managing code and research products in a “version control’ repository such as Github. Figshare and other data repositories. 
5. **Graphics**: The “grammar” of graphics: ggplot2 and extensions (ggmap, rasterVis, etc.)
6. **Spatial Data**: Spatial Libraries: raster, sp, rgeos, rgdal. Integrating ‘traditional GIS’ analyses with statistical modelling.  Data intersection (e.g. connecting points with polygons and rasters), overlays, zonal statistics, measuring autocorrelation (e.g. Moran’s I), spatial regression models. Example Application: Species distribution modeling: Use of dismo and raster packages to model species distributions. Example Application: processing MODIS data
7. **Use of raster, rgdal, and MODISTools** packages to process MODIS satellite data.
8. **High Performance Computing**: Introduction to foreach package and parallel processing.  
9. **Software Integration**: Language/software integration.  Use of the system() command. Calling various other programs from within R.
10. **Package Development**: Package structure and necessary components.  Things to consider when developing an R package. 

