---
title: "Package Introduction"
---

# Description

Each student will be expected to introduce a package (or two) that is relevant to their research interests in a 5 minute presentation during a class session.  The objectives are:

* Learn how to find/download/install a new package and learn how to use it
* Teach your peers about existing R packages that may be useful in their research

The presentation must include:

1. Brief introduction: what does the package do and why is it useful? (**1-2 slides, 1 minute**)
2. Author introduction: a short background (affiliation and other packages, etc.) on at least one of the package authors (**1 slide, 1 minute**)
2. Simple demonstration of package code: example input/output from the examples or custom coded examples (**2-3 slides, 3 minutes**)

There will not be time to actually run any code *on-the-fly* during your presentation.  Instead, copy the code and output into a presentation (powerpoint, etc.) so that you can simply display it.  See an [example presentation here](assets/PackagePresentation.pptx).

To select a package, I recommend starting with the [views on CRAN](https://cran.r-project.org/web/views/) for a topic of interest.  Then read the narrative in the task view for something interesting to you and install the package in R with `install.package("packagename")` in R and take a look at what it can do.  Most package functions include sample code that performs a function.    For example, if I was introducing the `dplyr` package, I might choose the `filter()` function.  If you look in the help you will find a section called "Examples" that you can use for your example code in your presentation.  All you have to do is copy-paste it from the help into the R console and them summarize what it's doing in your presentation.  For example, I might demonstrate (from the `filter()` documentation) that the following code will select all characters from Star Wars that are human.

```{r,message=FALSE}
library(dplyr)
filter(starwars, species == "Human")
```




