---
title: "Resources"
---

## Data Science
* [What classes should I take if I want to become a data scientist?](https://www.quora.com/What-classes-should-I-take-if-I-want-to-become-a-data-scientist)


## Getting Started with R

<div style="height: 10px;"></div>


- **[R Background](r_background.html):** We provide a background of who is using *R* and why 
- **[First Use of R](r_help.html):** If you have no background with *R*, this page will provide some details on file types and the workflow of using R and R-Studio. Note the description of `.R` scripts.  I would recommend that most of your work starts with a `.R` script, and then you build an `.Rmd` file from code in your script.
- **[R-Studio First Use](rmarkdown_help.html):** After you have installed *R* and R-Studio then this page will help you with building your first `.Rmd` file.  We will use this type of file heavily throughout the semester.
- **[R Visualization](r_visualization.html):** Some random links about *R* packages for visualization.
- **[R Cheat Sheets](r_cheat.html):** This page has links to one-page guides to different R packages and data science tools. 
- **[Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml):** A guide from Google on how to type clean code that allows your code to communicate with others.  Think [Elements of Style](https://www.amazon.com/Elements-Style-William-Strunk-ebook/dp/B005IT0V8O/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=&sr=).
* [A very short introduction to R](https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf)
* [R Markdown Cheat Sheet (PDF)](http://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf), a quick guide to the most commonly used markdown syntax, knitr options, and output formats.
* [R Markdown Reference Guide (PDF)](http://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf), a more comprehensive reference guide to markdown, knitr, and output format options.
* [Who's using R](http://r4stats.com/articles/popularity/)

## Infographic resources

* [Infographic Layout](http://www.r-bloggers.com/r-how-to-layout-and-design-an-infographic/)

## Learning more

For even more in-depth documentation see:

* [Advanced R](http://adv-r.had.co.nz) book for R users who want to improve their programming skills and understanding of the language. It should also be useful for programmers coming to R from other languages, as it explains some of R’s quirks and shows how some parts that seem horrible do have a positive side.
* The website for the [knitr package](http://yihui.name/knitr/). Knitr is an extremely powerful tool for dynamic content generation and the website has a wealth of documentation and examples to help you utilize it to its full potential.
* A detailed overview about writing your own [R Packages](http://r-pkgs.had.co.nz) by Hadley Wickham.  
