---
title: "Course Schedule"
---

Course content is designed to be flexible to accommodate student interest and abilities.  The order and timing of course topics may change as the semester progresses.  

**Readings**

In the table below, R4DS refers to [_R for Data Science_ by Garrett Grolemund and Hadley Wickham](http://r4ds.had.co.nz) and, while GCR refers to [_Geocomputation with R_ by Robin Lovelace, Jakub Nowosad, and Jannes Muenchow (CRC Press, 2018)](https://geocompr.robinlovelace.net/).

**Homework**
Homeworks are due at 5pm on the Friday of the week specified below.

| Week    |  Title   | Description |  Assignment | Readings | Package Presentation Group |
|:--|:--|:----------------------------------------|:---------|:---|---:|
| 8/28    | **Introduction & Overview** | Course Motivation & Objectives. Workflow & repeatable research in an era of big data. Getting started with R & RStudio. Data structures (vectors, matrices, data frames).| | [R4DS 1-2](http://r4ds.had.co.nz) |
| 9/4 | **Graphics** | The _grammar of graphics_: ggplot2 | Practice homework | [R4DS 3](http://r4ds.had.co.nz) |  |
| 9/11 | **Data Wrangling ** | Data Transformation: Filtering, selecting, transforming  | | [R4DS 4-5](http://r4ds.had.co.nz) | 1|
| 9/18 | **Data Wrangling 2** | Joining data | Homework #1: Graphics| [R4DS ](http://r4ds.had.co.nz) | 2 |
| 9/25 | **Spatial Vector Data** | Vector data processing. Integrating ‘traditional GIS’ analyses with statistical modelling.  Data intersection, overlays, zonal statistics |  | [GCR 1-2](https://geocompr.robinlovelace.net/) | 3 |
| 10/2 | **Spatial Raster Data** | Gridded spatial data |  Homework # 2: Data Wrangling | [GCR 3-4](https://geocompr.robinlovelace.net/) | 4|
| 10/9 | **Creating Workflows** | Example A 'mini' project: Sea level rise in Bangladesh | Project Proposal |  | 5|
| 10/16 | **Reproducible Research & Literate Programming ** | Data I/O. RMarkdown to create dynamic research outputs.  Publishing to github/word/html/etc.| Homework # 3 Spatial|  [R4DS 11, 26-30](http://r4ds.had.co.nz) | 6 |
| 10/23 | **APIs, time-series, and weather Data ** | Processing daily weather data from NOAA  |  | | 7|
| 10/30 | **Satellite Data Processing** | MODIS Satellite data |Homework # 4  |   | 8 |
| 11/6 | **High Performance Computing & Software Integration** | Parallel processing and high performance computing in R, Calling other programs from within R. | Project 1st draft for peer assessment| | 9 |
| 11/13 | **Dynamic Visualization** | Interactive web-based visualizations|  Peer Evaluation Due |[R4DS 28](http://r4ds.had.co.nz) | 10 |
| 11/20 | **Thanksgiving** | (no class)   |  | |
| 11/27 | **Modeling Basics**  |  Building and summarizing models | Second draft of project Due 12/1 at midnight |  [R4DS 23-25](http://r4ds.had.co.nz) |
| 12/4 | **Final Project Presentations** | | 5 minute presentation of your final project | |
| 12/14 | **Final Project Due in UBLearns** | | See <a href=Project.html>Project description for more information</a> |