---
title:  Final Project 2nd Draft / Building and summarizing models 
subtitle:  Building a species distribution model
week: 14
type: Task
reading:
  - Chapter [23-25 in R4DS](http://r4ds.had.co.nz)
tasks:
   - Commit second draft of final project to GitHub for review
   - Demonstrate a simple presence/absence model in spatial context. 
   - Model spatial dependence (autocorrelation) in the response. 
---

```{r, echo=FALSE, message=FALSE, results='hide', purl=FALSE}
source("functions.R")
source("knitr_header.R")
```

# Final Presentation

<div>
<object data="presentations/Conclusion.pdf" type="application/pdf" width="100%" height="600px"> 
  <p>It appears you don't have a PDF plugin for this browser.
   No biggie... you can <a href="presentations/Conclusion.pdf">click here to
  download the PDF file.</a></p>  
 </object>
 </div>
 <p><a href="presentations/Conclusion.pdf">Download the PDF</a></p>  

# Reading

```{r reading,results='asis',echo=F}
md_bullet(rmarkdown::metadata$reading)
```

# Tasks

```{r tasks,results='asis',echo=F}
md_bullet(rmarkdown::metadata$tasks)
```

# Exercise

Work through the [exercise illustrated here](13_SDM_Exercise.html).  You do not need to upload anything to github.
